
    <header>
        <h1><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Accesos</h1>
    </header>
    
    <div class="row">
    	<div class="col-md-12">
    		<div class="panel panel-default">
              <div class="panel-heading">
                <h3 class="panel-title">Lista de accesos</h3>
              </div>
              <div class="panel-body">
              	<table class="table table-bordered table-stripped">   
					<thead>
						<tr>
							<th>Nombre Usuario</th>
							<th>Fecha</th>
							<th>Dirección Ip</th>
						</tr>
					</thead>
					<tbody>
              		<?php foreach($lista_de_accesos as $acceso): ?>
						<tr>
							<td><?= $acceso['usuario_nombre']?></td>
							<td><?= $acceso['fecha_acceso']?></td>
							<td><?= $acceso['ip_acceso']?></td>
						</tr>
					<?php endforeach; ?>
					</tbody>
                </table>
              </div>
            </div>
    	</div>
    </div>
    