<header>
    <h1>
        <span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span>
        Asignar Recursos al Perfil
    </h1>
</header>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Información del Perfil</h3>
            </div>
            <div class="panel-body">
                <?= Html::formOpen("perfiles/asignar_recursos/". $perfil['id'],"class=\"form-horizontal\"") ?>
                <div class="row">
                    <div class="col-md-3">                    
                        <label for="fecha" class="col-sm-2 control-label">Perfil</label>
                        <input type="text" class="form-control" id="data_nombre" 
                            readonly name="data[nombre]" value="<?= $perfil['nombre']?>">     
                                                            
                    </div>
                    <div class="col-md-7">
                        <ul class="list-group">
                        <?php foreach($recursos as $recurso): 
                            $checked = '';
                            ?>
                            <?php if(intval($recurso['cuenta']) > 0): ?>
                                <?php $checked = ' checked '; ?>
                            <?php endif; ?>
                            <li class="list-group-item">
                            <label>
                                <input type="checkbox" class="recurso"
                                    id="recurso_<?=$recurso['id']?>" 
                                    name="recurso[<?=$recurso['id']?>]" 
                                    value="<?=$recurso['id']?>"
                                    <?= $checked ?>> <?=$recurso['controlador']?>/<?=$recurso['accion']?>
                            </label>
                            </li>
                        <?php endforeach; ?>
                        </ul>
                    </div>
                    <div class="col-md-2">                        
                        <?= Html::linkTo("Volver", "perfiles", 
                            "class=\"btn btn-default\"")?>   
                        <button type="submit" class="btn btn-success">Actualizar</button>
                    </div>
                </div>
                <?= Html::formClose()?>
            </div>
        </div>
    </div>
</div>