
<div class="jumbotron">
	<h1>Bienvenid@s</h1>
	<p>Te damos la más cordial de las bienvenidas a este proyecto creado con el Framework IsaliaPHP</p>
	<p>Este es el punto de inicio que puedes utilizar para crear tus proyectos sin tener que comenzar desde cero.</p>
	<p>
		<a class="btn btn-lg btn-primary" href="#" role="button">Ver documentación &raquo;</a>
	</p>
</div>


<script>
	function initialize() {}
</script>