<header>
    <h1>
        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
        Crear Usuario
    </h1>
</header>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Información del Usuario</h3>
            </div>
            <div class="panel-body">

            <?= Html::formOpen("usuarios/create","class=\"form-horizontal mt-2\"") ?>
                    <div class="form-group">
                        <label for="data_nombre" class="col-sm-2 control-label">Nombre</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="data_nombre" name="data[nombre]">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="data_login" class="col-sm-2 control-label">Login</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="data_login" name="data[login]">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="data_login" class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="data_email" name="data[email]">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="data_login" class="col-sm-2 control-label">Clave</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" id="data_clave" name="data[clave]">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="data_empresa_id" class="col-sm-2 control-label">Empresa</label>
                        <div class="col-sm-10">
                            <select class="form-control" id="data_empresa_id" name="data[empresa_id]">
                                <?= Html::optionsForSelect((new Empresa)->findAll("WHERE activa = 1"), "id", "razon_social");?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="data_perfil_id" class="col-sm-2 control-label">Perfil</label>
                        <div class="col-sm-10">
                            <select class="form-control" id="data_perfil_id" name="data[perfil_id]">
                                <?= Html::optionsForSelect((new Perfil)->findAll("WHERE activo = 1"), "id", "nombre");?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group text-right pr-2">
                    <?= Html::linkTo("Cancelar", "usuarios", 
                            "class=\"btn btn-default\"")?>
                        <button type="submit" class="btn btn-success">Crear</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>