<header>
    <h1>
        <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
        Editar Usuario
    </h1>
</header>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Información del Usuario</h3>
            </div>
            <div class="panel-body">
                <?= Html::formOpen("usuarios/edit/" . $current_item['id'], 
                "class=\"form-horizontal mt-2\"") ?>
                    <div class="form-group">
                        <label for="data_nombre" class="col-sm-2 control-label">Nombre</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" 
                                id="data_nombre" name="data[nombre]"
                                value="<?=$current_item['nombre']?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="data_login" class="col-sm-2 control-label">Login</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" 
                                id="data_login" name="data[login]"
                                value="<?=$current_item['login']?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="data_email" class="col-sm-2 control-label">Correo</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" 
                                id="data_email" name="data[email]"
                                value="<?=$current_item['email']?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="data_perfil_id" class="col-sm-2 control-label">Perfil</label>
                        <div class="col-sm-10">
                            <select class="form-control" id="data_perfil_id" name="data[perfil_id]">
                                <?= Html::optionsForSelect((new Perfil)->findAll("WHERE activo = 1"), "id", "nombre", $current_item['perfil_id']);?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group text-right pr-2">
                        <?= Html::linkTo("Cancelar", "usuarios", 
                            "class=\"btn btn-default\"")?>
                        <button type="submit" class="btn btn-info">Actualizar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>