
<header>
	<h1>
		<span class="glyphicon glyphicon-user" aria-hidden="true"></span>
		Lista de Usuarios
	</h1>
</header>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Usuarios</h3>
			</div>
			<div class="panel-body">
				<?= Html::linkTo("Crear Usuario", "usuarios/create",  "class=\"btn btn-success\"")?>
                <table class="table table-bordered table-stripped mt-2">              	
                    <thead>
                        <tr>
                            <th>Nombre</th>
							<th>Login</th>
							<th>Email</th>
							<th>Perfil</th>
							<th>Empresa</th>
							<th>Estado</th>
							<th>Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                	<?php foreach($list_of_items as $item):?>
                	<tr>
						<td><?= $item['nombre']?></td>
						<td><?= $item['login']?></td>
						<td><?= $item['email']?></td>
						<td><?= Perfil::getNombre($item['perfil_id'])?></td>
						<td><?= Empresa::getNombre($item['empresa_id'])?></td>
						<td><?= $item['activo'] == '1' ? 'Activo': 'Inactivo' ?></td>
						<td align="center">
                            <?= Html::linkTo("<i class='glyphicon glyphicon-pencil'></i>", "usuarios/edit/" . $item['id'], 
                            "class=\"btn btn-info btn-sm\" title=\"Editar Usuario\"")?>
							<?= Html::linkTo("<i class='glyphicon glyphicon-erase'></i>", "usuarios/reset_password/" . $item['id'], 
                            "class=\"btn btn-primary btn-sm\" title=\"Resetear clave\"")?>
							<?php if(intval($item['activo']) == 1): ?>
								<?= Html::linkTo("<i class='glyphicon glyphicon-minus-sign'></i>", "usuarios/cambiar_estado/" . $item['id'], 
                            		"class=\"btn btn-danger btn-sm\" title=\"Inactivar usuario\"")?>
							<?php else: ?>
							<?= Html::linkTo("<i class='glyphicon glyphicon-plus-sign'></i>", "usuarios/cambiar_estado/" . $item['id'], 
                            "class=\"btn btn-success btn-sm\" title=\"Activar usuario\"")?>
							<?php endif ?>
                		</td>
					</tr>
                	<?php endforeach;?>
                    </tbody>
                </table>
			</div>
		</div>
	</div>
</div>

