<header>
    <h1>
        <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
        Cambiar Contraseña
    </h1>
</header>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Información del Usuario</h3>
            </div>
            <div class="panel-body">
                <?= Html::formOpen("usuarios/reset_password/" . $usuario['id'], 
                "class=\"form-horizontal mt-2\" id=\"form_reset\"") ?>
                    <div class="form-group">
                        <label for="data_nombre" class="col-sm-2 control-label">Nombre</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" 
                                id="data_nombre" readonly name="nombre"
                                value="<?=$usuario['nombre']?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="data_clave" class="col-sm-2 control-label">Clave</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" 
                                id="nueva_clave" name="nueva_clave">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="data_clave" class="col-sm-2 control-label">Repetir Clave</label>
                        <div class="col-sm-10">
                            <input type="password" class="form-control" 
                                id="nueva_clave_repetir" name="nueva_clave_repetir">
                        </div>
                    </div>
                    <div class="form-group text-right pr-2">
                        <?= Html::linkTo("Cancelar", "usuarios", 
                            "class=\"btn btn-default\"")?>
                        <button type="button" class="btn btn-info" onclick="return validarFormulario();">Cambiar Clave</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    function validarFormulario()
    {
        let valor_clave_1 = $("#nueva_clave").val();
        let valor_clave_2 = $("#nueva_clave_repetir").val();

        if (valor_clave_1 === valor_clave_2) {
            $("#form_reset").submit();
        } else {
            return false;
        }
    }
</script>