<header>
    <h1>
        <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
        Editar Empresa
    </h1>
</header>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Información de la Empresa</h3>
            </div>
            <div class="panel-body">
                <?= Html::formOpen("empresas/edit/" . $current_item['id'], 
                "class=\"form-horizontal mt-2\"") ?>
                    <div class="form-group">
                        <label for="data_nombre" class="col-sm-2 control-label">Razón Social</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" 
                                id="data_razon_social" name="data[razon_social]"
                                value="<?=$current_item['razon_social']?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="data_url" class="col-sm-2 control-label">Rut</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" 
                                id="data_rut" name="data[rut]"
                                value="<?=$current_item['rut']?>">
                        </div>
                    </div>
                    <div class="form-group text-right pr-2">
                        <?= Html::linkTo("Cancelar", "empresas", 
                            "class=\"btn btn-default\"")?>
                        <button type="submit" class="btn btn-info">Actualizar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>