
<header>
	<h1>
		<span class="glyphicon glyphicon-link" aria-hidden="true"></span>
		Lista de Recursos
	</h1>
</header>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Recursos</h3>
			</div>
			<div class="panel-body">
				<?= Html::linkTo("Crear Recurso", "recursos/create",  "class=\"btn btn-success\"")?>
                <table class="table table-bordered table-stripped mt-2">              	
                    <thead>
                        <tr>
                            <th>Controlador</th>
							<th>Acción</th>
							<th>Estado</th>
							<th>Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                	<?php foreach($list_of_items as $item):?>
                	<tr>
						<td><?= $item['controlador']?></td>
						<td><?= $item['accion']?></td>
						<td><?= $item['activo'] == '1' ? 'Activo': 'Inactivo' ?></td>
						<td align="center">
                            <?= Html::linkTo("<i class='glyphicon glyphicon-pencil'></i>", "recursos/edit/" . $item['id'], 
                            "class=\"btn btn-info btn-sm\" title=\"Editar Recurso\"")?>
							<?php if(intval($item['activo']) == 1): ?>
								<?= Html::linkTo("<i class='glyphicon glyphicon-minus-sign'></i>", "recursos/cambiar_estado/" . $item['id'], 
                            		"class=\"btn btn-danger btn-sm\" title=\"Inactivar recurso\"")?>
							<?php else: ?>
							<?= Html::linkTo("<i class='glyphicon glyphicon-plus-sign'></i>", "recursos/cambiar_estado/" . $item['id'], 
                            "class=\"btn btn-success btn-sm\" title=\"Activar recurso\"")?>
							<?php endif ?>
                		</td>
					</tr>
                	<?php endforeach;?>
                    </tbody>
                </table>
			</div>
		</div>
	</div>
</div>

